### PR TITLE
AUI-3088 SF

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
@dustinryerson wrote: 

> Hey @ambrinchaudhary,
> 
> This is an update for AUI-3088.
> 
> I know the Alloy Editor project usually uses GitHub issues to fix bugs; would you like me to open an issue for this so it can be tracked on GitHub or will the JIRA ticket be enough?
> 
> Please let me know if you have any questions.
> 
> Thanks!

### CODE REVIEW

**Comment by antoniopol06** [comment]
Just started reviewing :) <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by antoniopol06** [comment]
Hi @dustinryerson !

I try to review it today. I will write some test to check this issue and after that I will fix it.

Thanks!

**Comment by dustinryerson** [comment]
Thank you @antoniopol06!

**Comment by antoniopol06** [comment]
Hi @dustinryerson 

I created [this issue](https://github.com/liferay/alloy-editor/issues/589)  on AlloyEditor and I am working on that.

**Comment by ChrisKian** [comment]
Hi @antoniopol06,

I wanted to see what the status of this issue is, and if there is anything I can do to help.

Thanks!

**Comment by antoniopol06** [comment]
Hi @ChrisKian ,

 [This issue](https://github.com/liferay/alloy-editor/issues/589) on AlloyEditor is fixed.

**Pull request closed without merging**
